on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:
  build:
    strategy:
      matrix:
        matrix:
          - runner: ubuntu-24.04
            name: sizer-x64-linux
          - runner: macos-15
            name: sizer-arm64-mac
          - runner: windows-2025
            name: sizer-x64-win.exe

    runs-on: ${{ matrix.matrix.runner }}

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.22.2

      - run: corepack enable

      - name: find pnpm cache path
        id: cache
        shell: sh
        run: echo "path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ${{ steps.cache.outputs.path }}
          key: v1-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - run: pnpm build

      - run: pnpm publint

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: ${{ runner.os == 'Linux' }}
        with:
          name: dist
          path: dist/**/*
          if-no-files-found: error
          retention-days: 1

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ matrix.matrix.name }}
          path: build/sizer-*
          if-no-files-found: error
          retention-days: 1

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.22.2

      - run: npm i -g corepack

      - name: find pnpm cache path
        id: cache
        run: echo "path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ${{ steps.cache.outputs.path }}
          key: v1-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.22.2

      - run: npm i -g corepack

      - name: find pnpm cache path
        id: cache
        run: echo "path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ${{ steps.cache.outputs.path }}
          key: v1-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - run: pnpm typecheck

  changesets:
    runs-on: ubuntu-latest
    needs: [build, lint, typecheck]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22.22.2

      - run: npm i -g corepack

      - name: find pnpm cache path
        id: cache
        run: echo "path=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ${{ steps.cache.outputs.path }}
          key: v1-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-${{ runner.os }}-pnpm-

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: dist
          path: dist/

      - name: Install dependencies
        run: pnpm i --development --frozen-lockfile

      - run: pnpm publint

      - name: Update release PR / Publish packages to `npm`
        id: changesets
        uses: changesets/action@v1
        with:
          title: Release
          commit: Release new version
          publish: pnpm changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}

      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        if: ${{ steps.changesets.outputs.published == 'true' }}
        with:
          name: sizer-arm64-mac
          path: build/
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        if: ${{ steps.changesets.outputs.published == 'true' }}
        with:
          name: sizer-x64-linux
          path: build/
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        if: ${{ steps.changesets.outputs.published == 'true' }}
        with:
          name: sizer-x64-win.exe
          path: build/

      - name: Upload binaries to release
        if: ${{ steps.changesets.outputs.published == 'true' }}
        run: gh release upload --clobber $(git tag) build/*
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
