on:
  push:
    branches:
      - main
  pull_request:

name: CI

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - run: corepack enable

      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: v1-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - run: corepack enable

      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: v1-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - run: pnpm typecheck

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - run: corepack enable

      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: v1-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-${{ runner.os }}-pnpm-

      - uses: actions/cache@v3
        with:
          path: ~/.pkg-cache
          key: v1-${{ runner.os }}-pkg-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-${{ runner.os }}-pkg-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - run: pnpm build
